manifests/cluster.pp, manifests/init.pp
monitoring_check has use_sensu, use_nagios, and use_consul for feature toggling. The ensure=> parameter does not follow the typical contract for 'ensure', as it is used only as a passthrough to sensu::check. It provides no functionality that the use_sensu parameter does not provide, and should be removed.
=> Remove the ensure option, as monitoring_checks are purged

manifests/init.pp, spec/defines/monitoring_check_spec.rb
- Reorganizes the docstrings and options. Matches docstring ordering to option ordering.
- Small fixups to docstring content.
- Adds a docstring for timeout that was missing.
- Remove unused nagios, nagios_custom, and aggregate options.
=> Fixup docstrings

.fixtures.yml
This fixes yelp/puppet-monitoring_check tests the quick way.
I will create an issue to fix them the right way later - the failure is coming from apt:key and I don't feel like doing that now, that area needs to be cleaned up anyway.
Here is a link to the actual change that fixes these tests:
https://github.com/somic/puppetlabs-apt/commit/ee51cf6929e1c51857ae43e720a32145df780d70
=> fix tests the quick way

manifests/params.pp, spec/classes/params_spec.rb
primary: @mrtyler 
The teams.json file is owned by the sensu user and exists in the /etc/sensu dir. Both of these are created by the sensu package.
This makes that requirement explicit so puppet can converge better. Internal ticket PAASTA-648.
=> Make the teams.json file depend on the sensu package existing

manifests/init.pp
Some checks should never alert at all, since the alerting is being done by a cluster check of many hosts. In this case, it would be nice to have the check not spawn a handler at all.
This change just creates a new, optional parameter of "handle", which is passed along to the sensu::check that is created.
=> Add option to not use handlers for a monitoring check

manifests/init.pp, spec/defines/monitoring_check_spec.rb
We were having an issue using both the parameters "handle" and "handlers" in our Sensu check. Sensu complained that using both parameters could cause one to overwrite the other.
We still want a way to spawn no handlers for some checks. To do that now, we will pass in an empty array to the "handlers" parameter.
=> To spawn no handers, send an empty array in the "handlers" param

manifests/init.pp, spec/defines/monitoring_check_spec.rb
This adds the `source` param to monitoring_check. 
I also refactored the merging of the `custom` param that goes into the sensu check a little - nothing major, just grouping together the merges.
Finally, I aligned the hashes in the specs.
=> add source parameter to monitoring_check class

files/check-cluster.rb, manifests/cluster.pp, spec/unit/check_cluster_spec.rb
Adding verbose, dryrun flag to aid in debugging, and using more clear output messages to hopefully make it clear that an 'OK' status for this check means the checking the cluster was successful, not necessarily that the output of the cluster check was 'OK'
=> Debug help

manifests/cluster.pp
The machinery for passing through these fields no longer exists, as we can't
depend on having the individual check to pull this information from. Removing
these comments, and making runbook mandatory, for clarity.
=> Removing comments on runbook, tip passthru

files/check-cluster.rb, spec/unit/check_cluster_spec.rb
Implementing another check on the ttl that Maksym suggested in his comment on commit f9ae6abc6ac4ee5d1284863e3029ed6c96b258a2
=> If the lock expires sooner than rtt to redis server, return ok

files/check-cluster.rb, manifests/cluster.pp, spec/unit/check_cluster_spec.rb
This PR changes the old target_interval into staleness_interval. I think this new name makes its purpose more clear.
It also adds this as a param to monitoring_check::cluster. Before, target_interval was part of the sensu_custom hash. By making it a parameter in itself, we can cleanly give it a default value.  Right now, it defaults to 12 hours, but that value is open to discussion.
In the cluster check, we look at the latest result from each individual check. In this latest result, we can see if the check passed or failed.  What staleness_interval allows us to do, is to ensure that this latest check result was created within a reasonable timeframe. For example, if a host runs a check, gives a result of 'OK', and then the box is abducted by aliens, Sensu would still have the latest result …
=> Default interval

files/check-cluster.rb
This updates the RedisAggregateCheck class to ensure that we don't
return the name of the cluster check when we query redis. This way, if
we have a failure, the cluster check should clear itself up
=> Omit check results with same name as cluster_name FIXES #65

files/check-cluster.rb, spec/unit/check_cluster_spec.rb
This gives output like this:
```
CheckCluster OK: Dry run cluster check successfully executed, with output: (CRITICAL: 6 OK out of 9 total. (66% OK, 80% threshold - Stale hosts: ["host1", "host2", "host3"]))
```
=> Display hosts in output

manifests/init.pp, spec/defines/monitoring_check_spec.rb
This is the initial start of a bigger set of changes across the infra.
Adding these tags won't make much difference to the sensu checks themselves, it'll just add a new JSON field which is an empty array.
This will be much more useful when handlers are adapted to deal with them.
=> Adding arbitrary tags (FIXED #71)

files/check-cluster.rb, spec/unit/check_cluster_spec.rb
Adds an option to specify a minimum number of nodes that should be in the cluster in order to pass OK the check
=> Minimum nodes

.fixtures.yml, manifests/init.pp, manifests/server_side.pp, spec/defines/monitoring_check_spec.rb, spec/defines/server_side_spec.rb
This change makes us more compliant with newer sensu-puppet, which now has "source" parameter on sensu::check. As a result, we no longer have to pass "source" through "custom" param.
The dark side of this change is that it makes us not compatible with older versions of sensu-puppet.
@solarkennedy - my plan is to prepare an internal r10k change and merge this PR right before shipping it all in one. Looking for a shipit on this PR but please don't merge it yet.
=> make source param work with newer sensu-puppet

Gemfile.lock, manifests/init.pp, spec/defines/monitoring_check_spec.rb
This gives us more flexibility to manage how each check is handled in each environment, region, etc.
See internal OPS-8177 for a specific use case.
For some reason, had to upgrade rspec-puppet - tests were failing with hiera data leaking between contexts, which made no sense to me - upgrade fixed it.
=> more flexible way to manage how events are handled

files/fleet_check.rb, manifests/server_side/install.pp
Please see comments inside the file for what it is. Essentially it's yet another higher-level abstraction for a situation when we want to generate multiple events for individual hosts from a central location. This use case is currently not covered by either server side checks or cluster checks.
First use case within Yelp is centralized check_aws_events.
This is a dark launch, nothing uses it. I want to get it merged, deploy it and start testing/iterating.
=> add fleet_check.rb

.fixtures.yml, manifests/init.pp
Recently merged PR into sensu-puppet added support for the subdue option on sensu::check. It would be useful to also have this feature in monitoring_check
Ref: https://github.com/sensu/sensu-puppet/pull/440
=> Adding support to pass the subdue option into sensu::check

manifests/init.pp, spec/defines/monitoring_check_spec.rb
Our internal sensu-puppet doesn't have subdue param on sensu::check yet because this change was merged fairly recently.
This change introduces a simple compat mechanism to allow us and anybody else who's not running fairly recent sensu-puppet, to continue using monitoring_check.
=> better compat with sensu-puppet for subdue param

manifests/init.pp
This transforms the error message from something like:
Unknown variable: '::sensu::check_notify'. at /etc/puppet/environments/masterbranch/vendor/modules/sensu/manifests/check.pp:147:28
into the much more helpful:
Error while evaluating a Function Call, monitoring_check local_smtp defined before the sensu class was included at /etc/puppet/environments/masterbranch/vendor/modules/monitoring_check/manifests/init.pp:266:7
=> Make the error useful when Sensu hasn't been included.

manifests/init.pp, manifests/server_side.pp
This is useful for passing extra information from server side checks that would be otherwise unavailable.
=> Add tags to server side checks

manifests/server_side.pp, spec/defines/server_side_spec.rb
=> Automatically inject executor hostname into server side checks

manifests/params.pp
When changes happen, the diff Puppet automatically prints is now actually useful
=> Pretty-print team_data.json

files/check-cluster.rb, spec/unit/check_cluster_spec.rb
It will prevent generating CRITICAL alert when check_cluster can't connect to redis due to DNS issues.
Also it should not alert as CRITICAL when there are no hosts with a cluster check in a region.
=> use UNKNOWN status for internal exceptions in check_cluster 

manifests/init.pp, spec/defines/monitoring_check_spec.rb
Sources must match /^[\w\.-]+$/. This enforces that behaviour.
=> Force sources to comply with the Sensu validation scheme

.travis.yml, files/remediation.sh, manifests/init.pp, manifests/remediation.pp, spec/defines/monitoring_check_spec.rb
This is a bit of a first pass/WIP of auto remediation.
Adding 3 lines to the monitoring_check definition:
use_remediation
remediation_action
remediation_retries
will wrap the check in a script. The script will run the check as normal. If it passes, the wrapper will pass the check output to stdout, and pass the check exit code correct. If the check fails, it will run the remediation script, recording that it has run it in a file called /tmp/$name. The number of times the remediation action will run can be set. Only once this number of attempts has been reached will the check properly fail, and page/ticket as appropriate.
It's a bit janky - some of the bash output could be cleaned up, and it may make more sense to move this to Ruby, but it works for now.
=> Add auto remediation

files/remediation.sh
Sometimes, you want the remediation action to happen without delay. This will allow it.
=> Allow the remediation action to be run, and immediately ticket/page/etc

.travis.yml, Gemfile, files/check-cluster.rb, spec/defines/monitoring_check_spec.rb, spec/unit/check_cluster_spec.rb
For situations where we need to trigger events not based on percentages but based on absolute number of hosts.
I want to experiment with some events using this mode. The change itself looks quite small so worst case scenario we will end up not using it and could remove it in the future.
=> add --num-critical to check-cluster.rb

files/check-cluster.rb
See internal OPSALERTS-10684 for exact exception.
Looks to me like after we get a list of hosts in `find_servers`, we could run into a race condition where we request json for a given server's check result from redis (in `last_execution` method) but don't get it. Suspect it's possible due to transient issues with redis or if host disappeared between a call to `find_servers` and a call to `last_execution` (say it was a spot instance).
Here we just make sure not to raise an exception. This host will have [] as its value as a result and will be filtered out in the first line of `summary` method.
=> handle exceptions better in last_execution method in check-cluster.rb

files/check-cluster.rb
My previous fix was bad, 'rescue []' ended up being applied to entire merge!
This fixes it.
=> improve exceptions handling harder

manifests/init.pp
This is so that elsewhere we can do:
ticket: "%{hiera('some::hiera::value')}"
to get an override into a cluster check. 
Deep merge doesn't do what I wanted, so I'm doing this instead, cc @somic
=> Ticket 'false'/'true' gets converted to bool

files/check-cluster.rb
For the case when --num-critical is used.
cc @solarkennedy @somic @keymone
=> Make the cluster check output make more sense

files/fleet_check.rb
When we try to resolve an event through API and get HTTP 404, it means event has already been resolved or client no longer exists in sensu.
In either case, we should remove this client from our list of clients where this check has failed (which we maintain in `fleet_check:#{check_name}` redis key).
=> handle HTTP 400 from sensu api better

spec/unit/check_cluster_spec.rb
ref: https://github.com/Yelp/puppet-monitoring_check/issues/116
Two tests are removed relating to non-implemented warning behaviour in the check_cluster code.
One of the tests puts its assert predicates in a block that is never called, and the other asserts an "OK" return status, not a warning as implied in the title/comment.
=> removed dead code, 

Gemfile, Gemfile.lock, spec/spec_helper.rb, spec/unit/check_cluster_spec.rb
Fixes https://github.com/Yelp/puppet-monitoring_check/issues/118 by enabling predicates, and tweaking expected values so that tests pass (the adjustments seem reasonable rather than slavish).
=> Turn on coverage of test code and fix exposed dead predicates/expects

files/check-cluster.rb
I was working with this the other week and noticed that the -C and -u options have help text that says the exact opposite of what they actually do. Instead of -C PERCENT being the minimum number bad before sending an alert, it's actually the minimum number *good* to keep from sending an alert. -u NUMBER appears to work the same way.
=> Fixing the help for -C and -u options to match actual functionality

files/check-cluster.rb, spec/unit/check_multi_cluster_spec.rb
Identify child cluster in multi-cluster notifications, and validate (in unit tests) that failing node hosts are identified.
=> Multi cluster messages

files/check-cluster.rb
This fixes ```Check failed to run: class or module required for rescue clause, ["/etc/sensu/plugins/check-cluster.rb:355```
=> fix rescue in check-cluster.rb

files/check-cluster.rb, spec/unit/check_cluster_spec.rb
I thought it was fixed but looks like it's not. Most recent occurrence is OPS-11608
@keymone @philipmulcahy @nosmo
=> fix [] -> {} in last_execution in cluster check

files/check_remote_sensu.rb, manifests/server_side/install.pp
This is for internal OPSIMP-2475.
The idea is to let a sensu cluster check events in remote sensu cluster. This is useful if remote sensu cluster is for some reason unable to run handlers - such as, for example, unable to hit pagerduty due to Internet connectivity issue at remote region.
=> add check_remote_sensu

manifests/init.pp
When remediation is defined for a check on a host where sensu is disabled via sensu_enabled in hiera, the monitoring_check::remediation class will attempt to install the file regardless. This is at best undesirable but in the current arrangement the installation will attempt to use ```${monitoring_check::params::etc_dir}/plugins/remediation.sh```, which will not exist on a host where sensu is disabled. 
This change simply gates the installation of remediation actions based on whether sensu is enabled.
=> Don't attempt to set up remediation when sensu is disabled

manifests/init.pp
The change introduced in #136 managed to leave $sudo_command unset when sensu is disabled due to improper tired if statements. This single if statement restores the desired behaviour.
=> Fix gating to set sudo_command when sensu is disabled

files/check-cluster.rb, spec/unit/check_multi_cluster_spec.rb
This change fixes a bug in multi-cluster mode whereby the set of client check results that is grouped by cluster_name wrongly includes the cluster_check (server) results, leading to "imaginary" nameless clusters being considered.
=> Exclude cluster result rows from child row set

files/check-cluster.rb, spec/unit/check_cluster_spec.rb, spec/unit/check_multi_cluster_spec.rb
multi-cluster mode requires multiple rows to be written - and redis locks are not reentrant. This fix hoists the lock acquisition above the loop.
=> Cluster name extraction fix lock

files/sensu_api_util.rb, manifests/server_side/install.pp
Improve code reuse by extracting some sensu api helper methods into their own module.
=> add sensu api client helper methods to SensuAPIUtil module

files/check-cluster.rb, files/check_server_side.rb, files/fleet_check.rb, spec/unit/check_cluster_spec.rb, spec/unit_helper.rb
My goal here is to avoid notifications (tickets or pages) when we couldn't connect to redis. Almost always it's a temporary issue with network or redis, and when it's not, we know about it through redis checks.
I think all these places have ```unknown``` method because they are within classes that inherit from ```Sensu::Plugin::Check::CLI```.
=> exit with unknown if failed to connect to redis

files/check-cluster.rb
@solarkennedy @keymone - it looks like https://github.com/Yelp/puppet-monitoring_check/blob/master/files/check-cluster.rb#L249 excludes silenced hosts from total, not includes them in it.
Requesting more pairs of eyes.
=> invert doc string

manifests/init.pp
Both these fields are optional and are used for providing more
information on the checks.
=> Add description and component fields to monitoring check.
