- files/send-test-sensu-alert
- manifests/params.pp
- spec/classes/params_spec.rb
- spec/defines/monitoring_check_spec.rb
- spec/fixtures/manifests/site.pp
This is a useful utility for all.
Broken tests should be due to @keymone?
> Added send-test-sensu-alert script

- files/check_server_side.rb
- files/tiny_redis.rb
Cleaned up a couple of minor points we observed during initial testing.
I will merge this after tests pass.
> several improvements in server side check

- files/send-test-sensu-alert
This feature is close to being usable for us!!!
> Make send-test-sensu-alert respect check ttl

- files/check_server_side.rb
- manifests/server_side.pp
- spec/defines/server_side_spec.rb
... by passing empty handlers array to placeholder
> suppress notifications from server-side placeholder

- files/check_server_side.rb
- spec/unit/check_server_side_spec.rb
- spec/unit_helper.rb
Used tests for check-cluster.rb as an example
> add some unit tests for check_sever_side.rb

- .fixtures.yml
- spec/defines/monitoring_check_spec.rb
- spec/defines/server_side_spec.rb
Same as https://github.com/Yelp/sensu_handlers/pull/40
> repoint apt in fixtures to proper upstream

- files/check-cluster.rb
Original MR had the wrong check for the array
Also, failed host returns an array for the host key, which was causing
the map to fail
> Fixing failing host output

- files/fleet_check.rb
- manifests/server_side/install.pp
Minor fixes, I am going to merge this once travis tests pass.
> fleet_check.rb fixes

- files/fleet_check.rb
I will merge this after travis runs.
> fix more bugs in fleet check

- manifests/check_cluster_install.pp
- manifests/params.pp
- manifests/server_side/install.pp
- manifests/tiny_redis_install.pp
- spec/classes/params_spec.rb
- spec/classes/server_side_install_spec.rb
Fixing the paths and user/groups so that it works as expected on windows platforms.
> Making this work for windows.

- files/fleet_check.rb
Comments are welcome, by default I will just merge this soon.
> fleet check improvements

- .travis.yml
This should make up for any speed lost by installing bundler ourselves or whatever. (assuming it is green)
> Don't use sudo to use docker in travis

- Gemfile
- Gemfile.lock
- files/check-cluster.rb
- files/tiny_redis.rb
- spec/defines/monitoring_check_spec.rb
- spec/unit/check_cluster_spec.rb
- spec/unit/tiny_redis_spec.rb
The initial idea was to handle dns failures better in cluster-check.rb
Also I updated the puppet version, all related gems and removed some rspec warnings.
> handle dns failures better in cluster check

- manifests/init.pp
This makes writing times more consistent.
> Allow realert_every to be written in human readable formats

- files/tiny_redis.rb
To work around transient failures.
> add retry to redis connection check in tiny_redis

- files/check-cluster.rb
@somic what do you think about this? I need it for OPS-10102 internally
> Sometimes, we want to ignore cluster checks with no hosts

- files/remediation.sh
Primary: @pauloconnor 
CC: @chillmatik
I had trouble figuring out what might be wrong in internal ticket OPS-10459.
So I tried to change the way the script works in the following ways:
* Changed retries to max_attempts to help the logic read better
* Be verbose and let users know that remediation is running or not, and why
* Un-nest the code to fetch the current attempts from a file, and default to 0
* Print the output of the check and the remediation as soon as available
* Never override the CHECK_EXITCODE (let people use `alert_after` instead if they want to suppress alerts
> Hopefully make the remediation logic simpler

- Gemfile
- Gemfile.lock
- files/check-cluster.rb
- spec/spec_helper.rb
- spec/unit/check_cluster_spec.rb
- spec/unit/check_multi_cluster_spec.rb
- spec/unit_helper.rb
Provides functionality suggested in #124, and improves test coverage.
I'd like to go a little further in terms of refactoring the existing implementation (combining it with the new methods) if this change is acceptable.
I (as a ruby newbie) await  style feedback eagerly.
> Multi cluster check

- files/fleet_check.rb
> add option in fleet check to let irc_channels default to value from team data

- files/check_remote_sensu.rb
> json output option for check_remote_sensu.rb

- files/check-cluster.rb
Existing lock (not yet timed out from previous run) appears to be common and benign, and multi-cluster should not be making a fuss about it - the check should succeed.
> pre-existing redis lock no longer causes multi-cluster to fail noisily

- files/tiny_redis.rb
> retry redis socket to avoid getaddrinfo errors

- files/check_remote_sensu.rb
Makes filter argument optional.
> better filter in check_remote_sensu

- files/sensu_api_util.rb
> typo of the century!

- manifests/init.pp
- spec/defines/monitoring_check_spec.rb
This should fix issues where commands have arguments. OPSIMP-3087
> Quote commands
